#!/usr/bin/env bash
# Regenerate all skill/memory index files from frontmatter.
# Writes: .ai/skills/SKILLS_INDEX.md
#         .ai/global_memory/GLOBAL_MEMORY_INDEX.md
#         .ai/skills/<skill>/memory/MEMORY_INDEX.md  (for each skill that has memory/)
# Run this whenever you add, rename, or remove a memory or skill file.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Extract a single YAML frontmatter field from a markdown file.
# Returns empty string if not found.
get_field() {
  local file="$1" field="$2"
  awk -v field="$field" '
    BEGIN { in_fm = 0 }
    /^---[[:space:]]*$/ { if (in_fm) exit; in_fm = 1; next }
    in_fm {
      pattern = "^" field ":[[:space:]]*"
      if (match($0, pattern)) {
        val = substr($0, RLENGTH + 1)
        gsub(/^["\047]|["\047]$/, "", val)
        print val
        exit
      }
    }
  ' "$file"
}

# Build the index file for a directory of memory files (global_memory/ or skill memory/).
build_memory_index() {
  local dir="$1" title="$2" index_filename="$3"
  local index="$dir/$index_filename"
  local always_lines=() ondemand_lines=()

  shopt -s nullglob
  for f in "$dir"/*.md; do
    local base; base="$(basename "$f")"
    [[ "$base" == "$index_filename" || "$base" == "GLOBAL_MEMORY.md" ]] && continue

    local name desc scope line
    name=$(get_field "$f" name);             [ -z "$name" ]  && name="$base"
    desc=$(get_field "$f" description);      [ -z "$desc" ]  && desc="(no description)"
    scope=$(get_field "$f" scope);           [ -z "$scope" ] && scope="on-demand"

    line="- [$name]($base) · \`$scope\` · $desc"
    if [[ "$scope" == "always" ]]; then
      always_lines+=("$line")
    else
      ondemand_lines+=("$line")
    fi
  done
  shopt -u nullglob

  {
    echo "# $title"
    echo ""
    echo "> AUTO-GENERATED by \`.ai/build_indexes.sh\` — do not edit manually."
    echo ""
    echo "## Always"
    echo ""
    echo "> Loaded on every task."
    echo ""
    if [ ${#always_lines[@]} -eq 0 ]; then echo "_(none)_"; else printf '%s\n' "${always_lines[@]}"; fi
    echo ""
    echo "## On-demand"
    echo ""
    echo "> Loaded only when description is relevant to the current task."
    echo ""
    if [ ${#ondemand_lines[@]} -eq 0 ]; then echo "_(none)_"; else printf '%s\n' "${ondemand_lines[@]}"; fi
  } > "$index"

  echo "  built: ${index#$SCRIPT_DIR/}"
}

# Build SKILLS_INDEX.md for the skills directory.
# Skills can be a single file <name>.md or a folder <name>/<name>.md.
build_skills_index() {
  local dir="$SCRIPT_DIR/skills"
  local index="$dir/SKILLS_INDEX.md"
  local always_lines=() ondemand_lines=()

  shopt -s nullglob
  for entry in "$dir"/*; do
    local base; base="$(basename "$entry")"
    [[ "$base" == "SKILLS_INDEX.md" || "$base" == "SKILLS_README.md" ]] && continue

    local main_file="" relpath=""
    if [ -f "$entry" ] && [[ "$entry" == *.md ]]; then
      main_file="$entry"
      relpath="$base"
    elif [ -d "$entry" ] && [ -f "$entry/$base.md" ]; then
      main_file="$entry/$base.md"
      relpath="$base/$base.md"
    else
      continue
    fi

    local name desc scope line
    name=$(get_field "$main_file" name);         [ -z "$name" ]  && name="$base"
    desc=$(get_field "$main_file" description);  [ -z "$desc" ]  && desc="(no description)"
    scope=$(get_field "$main_file" scope);       [ -z "$scope" ] && scope="on-demand"

    line="- [$name]($relpath) · \`$scope\` · $desc"
    if [[ "$scope" == "always" ]]; then
      always_lines+=("$line")
    else
      ondemand_lines+=("$line")
    fi
  done
  shopt -u nullglob

  {
    echo "# Skills index"
    echo ""
    echo "> AUTO-GENERATED by \`.ai/build_indexes.sh\` — do not edit manually."
    echo ""
    echo "## Always"
    echo ""
    echo "> Skills active on every task."
    echo ""
    if [ ${#always_lines[@]} -eq 0 ]; then echo "_(none)_"; else printf '%s\n' "${always_lines[@]}"; fi
    echo ""
    echo "## On-demand"
    echo ""
    echo "> Skills loaded only when description is relevant to the current task."
    echo ""
    if [ ${#ondemand_lines[@]} -eq 0 ]; then echo "_(none)_"; else printf '%s\n' "${ondemand_lines[@]}"; fi
  } > "$index"

  echo "  built: ${index#$SCRIPT_DIR/}"
}

echo "Rebuilding index files in .ai/..."

[ -d "$SCRIPT_DIR/global_memory" ] && build_memory_index "$SCRIPT_DIR/global_memory" "Global memory index" "GLOBAL_MEMORY_INDEX.md"
[ -d "$SCRIPT_DIR/skills" ]        && build_skills_index

shopt -s nullglob
for skill_mem in "$SCRIPT_DIR"/skills/*/memory; do
  [ -d "$skill_mem" ] || continue
  build_memory_index "$skill_mem" "$(basename "$(dirname "$skill_mem")") memory index" "MEMORY_INDEX.md"
done
shopt -u nullglob

echo "done."
